name: 'Analyze Dart'
description: 'Analyze your project''s Dart code, including Flutter'
author: 'Zennon Gosalvez'
inputs:
  fail-on-warnings:
    description: 'The action fails if any warning was found. This will always fail on errors. Optional. Default: `false`'
    default: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`'
    default: ./
  analysis-options-file:
    description: 'The path to the `analysis_options.yaml` file relative to the `working-directory`. The analyzer will only use the file if it exists. Optional. Default: `analysis_options.yaml`'
    default: analysis_options.yaml
  dartfmt-line-length:
    description: 'The default line length used by dartfmt. Default: `80`'
    default: 80
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'green'
