name: 'Analyze Dart'
description: 'Analyze your project''s Dart code, including Flutter'
author: 'Zennon Gosalvez'
inputs:
  fail-on-infos:
    description: 'The action fails if any info was found. This will always fail on errors. Optional. Default: `false`'
    default: false
  fail-on-warnings:
    description: 'The action fails if any warning was found. This will always fail on errors. Optional. Default: `false`'
    default: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`'
    default: ./
  line-length:
    description: 'The maximum line length. Optional. The formatter will use its default: `80`'
  ignore-suffixes:
    description: 'Ignore the specified suffix, split multi suffixes with `|`'
    default: '.g.dart|.freezed.dart'

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'green'
